# Generated by Django 5.1 on 2024-08-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("score", models.FloatField(verbose_name="成绩")),
            ],
        ),
    ]
